/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import client.UDPClient;
import java.io.IOException;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import server.UDPServer;

/**
 *
 * @author Judah Holanda Correia Lima <judahholanda7@gmail.com>
 */
public class mainWindow extends javax.swing.JFrame {

   /**
    * Creates new form mainWindow
    */
   private UDPClient client;
   private UDPServer server;

   public mainWindow() {
      try {
         initComponents();
         this.client = new UDPClient(jTextFieldAddress, jButtonConnect, jTextFieldToSend, jTextAreaConsole, jButtonSend);
         this.server = new UDPServer(jTextAreaConsole, client);
         this.server.start();
      } catch (IOException ex) {
         Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jTextAreaConsole = new javax.swing.JTextArea();
      jTextFieldToSend = new javax.swing.JTextField();
      jButtonSend = new javax.swing.JButton();
      jTextFieldAddress = new javax.swing.JTextField();
      jButtonConnect = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jTextAreaConsole.setEditable(false);
      jTextAreaConsole.setColumns(20);
      jTextAreaConsole.setRows(5);
      jScrollPane1.setViewportView(jTextAreaConsole);

      jTextFieldToSend.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldToSendActionPerformed(evt);
         }
      });

      jButtonSend.setText("Send");
      jButtonSend.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSendActionPerformed(evt);
         }
      });

      jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldAddressActionPerformed(evt);
         }
      });

      jButtonConnect.setText("Connect");
      jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonConnectActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jTextFieldToSend)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButtonSend))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jTextFieldAddress)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButtonConnect)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonConnect))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jTextFieldToSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonSend))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void send() {
      client.send(jTextFieldToSend.getText());
      jTextFieldToSend.setText("");
   }

   private void connect() {
      try {
         client.connect(jTextFieldAddress.getText());
      } catch (SocketException ex) {
         Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
      }
   }

   private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
      send();
   }//GEN-LAST:event_jButtonSendActionPerformed

   private void jTextFieldToSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldToSendActionPerformed
      send();
   }//GEN-LAST:event_jTextFieldToSendActionPerformed

   private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
      connect();
   }//GEN-LAST:event_jButtonConnectActionPerformed

   private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
      connect();
   }//GEN-LAST:event_jTextFieldAddressActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new mainWindow().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonConnect;
   private javax.swing.JButton jButtonSend;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextAreaConsole;
   private javax.swing.JTextField jTextFieldAddress;
   private javax.swing.JTextField jTextFieldToSend;
   // End of variables declaration//GEN-END:variables
}
